#ShootOFF Configuration
#Fri Mar 13 07:54:00 CDT 2026
shootoff.arena.calibrated.behavior=ONLY_IN_BOUNDS
shootoff.arena.calibrated.exposure=true
shootoff.arena.notified.perspective=false
shootoff.arena.show.markers=false
shootoff.diagnosticmessages.chime.muted=
shootoff.errorreporting=true
shootoff.firstrun=false
shootoff.greenlasersound=C\:\\Users\\henri\\Desktop\\Antigravity\\ShootOFF\\sounds\\walther_ppq.wav
shootoff.greenlasersound.use=false
shootoff.ignorelasercolor=None
shootoff.ipcams=
shootoff.malfunctions.probability=10.0
shootoff.malfunctions.use=false
shootoff.markerradius=4
shootoff.redlasersound=C\:\\Users\\henri\\Desktop\\Antigravity\\ShootOFF\\sounds\\walther_ppq.wav
shootoff.redlasersound.use=false
shootoff.virtualmagazine.capacity=7
shootoff.virtualmagazine.use=false
shootoff.webcams=
shootoff.webcams.distances=
shootoff.webcams.recording=
