#ShootOFF Configuration
#Fri Mar 27 20:01:16 CDT 2026
shootoff.arena.calibrated.behavior=ONLY_IN_BOUNDS
shootoff.arena.calibrated.exposure=true
shootoff.arena.calibration.mode=AUTO_GREEN
shootoff.arena.notified.perspective=false
shootoff.arena.show.markers=false
shootoff.arena.x=1930.0
shootoff.arena.y=-328.0
shootoff.diagnosticmessages.chime.muted=
shootoff.errorreporting=true
shootoff.firstrun=false
shootoff.greenlasersound=C\:\\Users\\henri\\Desktop\\Antigravity\\ShootOFF\\sounds\\walther_ppq.wav
shootoff.greenlasersound.use=false
shootoff.ignorelasercolor=green
shootoff.ipcams=
shootoff.malfunctions.probability=10.0
shootoff.malfunctions.use=false
shootoff.markerradius=4
shootoff.redlasersound=C\:\\Users\\henri\\Desktop\\Antigravity\\ShootOFF\\sounds\\walther_ppq.wav
shootoff.redlasersound.use=false
shootoff.virtualmagazine.capacity=7
shootoff.virtualmagazine.use=false
shootoff.webcams=
shootoff.webcams.distances=null|200
shootoff.webcams.recording=
